global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # The labels to add to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'master'

{% if prometheus_rule_files is defined %}
# Rule files specifies a list of files from which rules are read.
rule_files:
  {% for (key, value) in prometheus_rule_files.iteritems() %}
  - {{ prometheus_rule_path }}/{{ value.dest }}
  {% endfor %}
{% endif %}

# A list of scrape configurations.
scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 10s
    scrape_timeout:  10s
    static_configs:
      - targets: ['192.168.100.50:9090']

  - job_name: "node"
    file_sd_configs:
      - files:
        - '{{ prometheus_file_sd_config_path }}/*.json'
        - '{{ prometheus_file_sd_config_path }}/*.yml'
        - '{{ prometheus_file_sd_config_path }}/*.yaml'
    
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['192.168.100.50:9100']
        labels:
          group: 'server'

      - targets: ['192.168.100.51:9100']
        labels:
          group: 'client'

      - targets: ['192.168.100.51:24231']
        labels:
          group: 'td-agent'

      - targets: ['192.168.100.52:9100']
        labels:
          group: 'client'

      - targets: ['192.168.100.52:24231']
        labels:
          group: 'td-agent'
